name: wamp
version: 0.0.6
author: George Moschovitis <george.moschovitis@gmail.com>
description: An implementation of the WAMP (http://wamp.ws) protocol for Dart.
homepage: https://github.com/gmosx/dart-wamp
dependencies:
  browser: any
